# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :distribute do
    gradle(task: 'assemble', build_type: 'release')
    firebase_app_distribution(
	service_credentials_file: "firebase_credentials.json",
    app: ENV['FIREBASE_APP_ID'],
	release_notes_file: "action_config/release_notes.txt",
	groups_file: "action_config/groups.txt"
    )
  end

  desc "Submit a new Internal Build to Google Play Console"
      lane :internal do
        gradle(task: "clean bundleRelease")
        upload_to_play_store(
          track: 'internal',
          release_status: 'draft',
          in_app_update_priority: 5,
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
        )
  end

  desc "Deploy a new version to the Google Play"
    lane :production do
      gradle(task: "clean bundleRelease")
      upload_to_play_store(
          release_status: 'draft',
          in_app_update_priority: 5,
          skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
      )
    end
end
