name: AppDistribution

on:
  push:
    branches: [ "app_distribution" ]
  pull_request:
    branches: [ "app_distribution" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        ache: gradle

    - name: Grant Permission to Execute
      run: chmod +x gradlew

    - name: Install bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Configure Keystore
      run: |
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
        echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
      env:
        ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

    - name: Configure Local Properties
      run: |
        echo "API_BASE_URL=$BASE_URL" >> local.properties
        echo "GMS_ADS_APP_ID=$ADS_APP_ID" >> local.properties
      env:
        BASE_URL: ${{ secrets.API_BASE_URL }}
        ADS_APP_ID: ${{ secrets.GMS_ADS_APP_ID }}

    - name: Create Firebase Service Credentials file
      run: |
        echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
        base64 -d -i firebase_credentials.json.b64 > firebase_credentials.json
      env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with App Distribution
      run: bundle exec fastlane distribute
      env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
